version: "3"
services:
  cobalt_web:
    build: ./cobalt_web
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
    logging:
        driver: json-file
        options:
            max-file: "1"
            max-size: 10m
  cobalt_parser:
    build: ./cobalt_parser
    env_file:
      - .env
    volumes:
      - "${COBALT_LOGS_PATH}:/logs"
    depends_on:
      - cobalt_web
    restart: always
    logging:
        driver: json-file
        options:
            max-file: "1"
            max-size: 10m
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - "./redis-data:/data"